name: Build on Main

on:
  push:
    branches:
      - komari-optimal

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Synchronize Go module metadata
        run: go mod tidy

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
          VERSION: ${{ github.sha }}
        run: |
          BINARY_NAME=komari-agent-${{ matrix.goos }}-${{ matrix.goarch }}
          go build -trimpath -ldflags="-X github.com/komari-monitor/komari-agent/version.CurrentVersion=${VERSION}" -o $BINARY_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: komari-agent-${{ matrix.goos }}-${{ matrix.goarch }}
          path: komari-agent-${{ matrix.goos }}-${{ matrix.goarch }}*
